CPO-58: case-payment-orders-api on prod
hmcts/cnp-flux-config pull request #10718
Opened 2021-07-29 08:29 UTC by sullivangareth

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CPO-58

### Change description ###

flux config to add case payment orders api microservice to prod

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2021-07-29 08:37 UTC, timja commented on k8s/namespaces/cpo/case-payment-orders-api/prod.yaml
> +        S2S_AUTHORIZATIONS_XUI_ID: xui_webapp
this is already set
```suggestion
```

2021-07-29 08:37 UTC, timja commented on k8s/namespaces/cpo/case-payment-orders-api/prod.yaml
> +        S2S_AUTHORIZATIONS_XUI_PERMISSION: R
isn't this already set as well?

2021-07-29 08:38 UTC, timja requested changes
cpo is missing from https://github.com/hmcts/cnp-flux-config/blob/master/k8s/prod/common-overlay/kustomization.yaml

2021-07-29 09:15 UTC, sullivangareth commented on k8s/namespaces/cpo/case-payment-orders-api/prod.yaml
> +        S2S_AUTHORIZATIONS_XUI_PERMISSION: R
Fixed in e0ae204

2021-07-29 09:15 UTC, sullivangareth commented on k8s/namespaces/cpo/case-payment-orders-api/prod.yaml
> +        S2S_AUTHORIZATIONS_XUI_ID: xui_webapp
Fixed in e0ae204

2021-07-29 12:54 UTC, smathangi commented
Please replace these entries with wildcard one as prod in place. Also please sync with latest master
https://github.com/hmcts/cnp-flux-config/blob/CPO-58/CODEOWNERS#L79-L81

2021-07-29 15:00 UTC, smathangi submitted a review, later dismissed

2021-07-30 12:03 UTC, danlysiak requested changes
Looks like we're missing `identity.yaml` for prod?

2021-07-30 13:26 UTC, danlysiak approved these changes

2021-07-30 13:42 UTC, cakeben approved these changes

2021-07-30 13:51 UTC, merged