Ccd 1737 Kustomize test-stubs-service AAT Only
hmcts/cnp-flux-config pull request #10903
Opened 2021-08-09 14:08 UTC by nathan-clark

https://tools.hmcts.net/jira/browse/CCD-1737

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-08-10 09:40 UTC, smathangi submitted a review, later dismissed

2021-08-16 23:52 UTC, MSancaktutar submitted a review, later dismissed
lgtm

2021-08-17 09:46 UTC, smathangi submitted a review, later dismissed

2021-08-19 08:31 UTC, timja commented on k8s/namespaces/ccd/ccd-test-stubs-service/ccd-test-stubs-service.yaml
> -      image: hmctspublic.azurecr.io/ccd/test-stubs-service:prod-342a36d-20210816124144   #{"$imagepolicy": "flux-system:ccd-test-stubs-service"}
this comment should be maintained it's how flux2 updates images

2021-08-19 08:32 UTC, timja requested changes

2021-08-19 08:32 UTC, timja commented on k8s/namespaces/ccd/ccd-test-stubs-service/ccd-test-stubs-service.yaml
> -      image: hmctspublic.azurecr.io/ccd/test-stubs-service:prod-342a36d-20210816124144   #{"$imagepolicy": "flux-system:ccd-test-stubs-service"}
this comment should be maintained it's how flux2 updates images

2021-08-19 12:56 UTC, timja approved these changes

2021-08-20 06:50 UTC, MSancaktutar approved these changes

2021-08-20 06:51 UTC, merged