Ccd 1737 Kustomize case-print-service.yaml
hmcts/cnp-flux-config pull request #10910
Opened 2021-08-10 10:45 UTC by nathan-clark

https://tools.hmcts.net/jira/browse/CCD-1737

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-08-19 08:39 UTC, timja requested changes
looks good apart from missing the image policy

2021-08-19 08:39 UTC, timja commented on k8s/namespaces/ccd/ccd-case-print-service/ccd-case-print-service.yaml
>        image: hmctspublic.azurecr.io/ccd/case-print-service:prod-f7d2085-20210807004743
https://github.com/hmcts/cnp-flux-config/blob/master/apps/ccd/ccd-case-print-service/image-policy.yaml
```suggestion
      image: hmctspublic.azurecr.io/ccd/case-print-service:prod-f7d2085-20210807004743  #{"$imagepolicy": "flux-system:ccd-case-print-service"}
```

2021-08-19 08:39 UTC, timja commented
you also have conflicts with master

2021-08-20 11:17 UTC, MSancaktutar approved these changes

2021-08-23 08:36 UTC, cakeben approved these changes

2021-08-23 08:37 UTC, merged