DFPL-404: Commenting out since our release PR is not building
hmcts/cnp-flux-config pull request #13765
Opened 2022-01-25 14:15 UTC by SomeshRA

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DFPL-404

### Change description ###
Commenting out since our release PR is not building

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-01-25 14:17 UTC, timja requested changes
please cleanup your namespace

2022-01-25 14:34 UTC, SomeshRA commented
> please cleanup your namespace

Cleaned up all the pods. But sill failing with this error 
39m         Warning   FailedCreate                      statefulset/fpl-case-service-pr-3308-es-master                              create Pod fpl-case-service-pr-3308-es-master-0 in StatefulSet fpl-case-service-pr-3308-es-master failed error: pods "fpl-case-service-pr-3308-es-master-0" is forbidden: failed quota: fpl-quota: must specify requests.cpu,requests.memory
22s         Warning   FailedCreate                      statefulset/fpl-case-service-pr-3308-es-master                              create Pod fpl-case-service-pr-3308-es-master-0 in StatefulSet fpl-case-service-pr-3308-es-master failed error: pods "fpl-case-service-pr-3308-es-master-0" is forbidden: failed quota: fpl-quota: must specify requests.cpu,requests.memory

2022-01-25 15:29 UTC, hannah38 approved these changes

2022-01-26 08:42 UTC, cakeben approved these changes

2022-01-26 08:43 UTC, merged