Private Law ithc environment setup
hmcts/cnp-flux-config pull request #14661
Opened 2022-03-09 15:17 UTC by AlokDatta

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PRL-955

### Change description ###
ITHC environment creation setup

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-03-09 16:02 UTC, shashisk97 approved these changes

2022-03-09 16:11 UTC, timja requested changes

2022-03-09 16:11 UTC, timja commented on k8s/namespaces/private-law/prl-dgs/ithc.yaml
> +apiVersion: helm.fluxcd.io/v1
ithc.yaml should only be overriding config not supporting all the values

2022-03-09 20:48 UTC, timja commented on k8s/namespaces/private-law/prl-cos/ithc.yaml
> +apiVersion: helm.fluxcd.io/v1
this file and prl-dgs don't appear to be referenced anywhere.

you're also using flux v2 for your identity and namespace which _may_ work but I _think_ generally you're recommended to use flux v1 outside of preview for now.

2022-03-10 14:38 UTC, AlokDatta commented
ITHC testing has been marked as not required, therefore, closing the PR for now.

2022-03-10 14:38 UTC, closed without merging