adding namespaces for rpts
hmcts/cnp-flux-config pull request #14663
Opened 2022-03-09 16:53 UTC by amstevenson

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-03-09 17:20 UTC, damongreen123 approved these changes

2022-03-09 20:41 UTC, timja requested changes

2022-03-09 20:41 UTC, timja commented on k8s/namespaces/rpts/kustomization.yaml
> -- namespace.yaml
this should be kept here you should not be adding namespace to other files

2022-03-14 09:52 UTC, timja approved these changes

2022-03-14 10:14 UTC, merged