updating kustomisation for batch tests
hmcts/cnp-flux-config pull request #14889
Opened 2022-03-21 14:14 UTC by larslunde-hmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-03-21 14:20 UTC, timja submitted a review, later dismissed

2022-03-22 10:11 UTC, thomast1906 requested changes
Please update imagepolicy or it will update to pr-26*

2022-03-22 15:20 UTC, larslunde-hmcts commented on k8s/namespaces/fees-pay/ccpay-callback-function/ithc.yaml
> +      image: hmctspublic.azurecr.io/ccpay/callback-function:pr-73-095a237-20220301120423 #{"$imagepolicy": "flux-system:ithc-ccpay-callback-function"}
updated image policy to reflect pr-73.

2022-03-23 12:59 UTC, thomast1906 approved these changes

2022-04-24 03:38 UTC, closed without merging