updating ccpay-callback-function production
hmcts/cnp-flux-config pull request #15009
Opened 2022-03-25 16:05 UTC by larslunde-hmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-03-25 16:15 UTC, timja requested changes
this doesn't look right, the sealed secret should still be of type sealed secret

2022-03-28 17:00 UTC, hannah38 approved these changes

2022-03-28 19:00 UTC, timja approved these changes

2022-05-06 14:06 UTC, anoojhmcts approved these changes

2022-05-06 15:50 UTC, pats-john approved these changes

2022-05-06 15:50 UTC, pats-john commented
Merging the Customisation changes to Production....

2022-05-06 15:50 UTC, merged