Update prod.yaml
hmcts/cnp-flux-config pull request #15024
Opened 2022-03-28 11:09 UTC by Majid-justice

https://tools.hmcts.net/jira/browse/FACT-940

adding  IDAM_UPDATE_USER_URL: https://idam-api.platform.hmcts.net/api/v1/users/

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-03-28 11:40 UTC, timja requested changes
Can you adjust the codeowners file please? This shouldn’t require platform ops approval

2022-03-28 13:09 UTC, Majid-justice commented
updated codeowners file

2022-03-29 08:16 UTC, timja approved these changes

2022-03-29 09:24 UTC, NatashaAlker approved these changes

2022-03-29 09:25 UTC, merged