Sscs 9588 kustomize hearings api
hmcts/cnp-flux-config pull request #15058
Opened 2022-03-29 16:04 UTC by dattipoeHMCTS

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/SSCS-9588

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-03-30 07:04 UTC, chrisorisawayi commented on k8s/namespaces/sscs/sscs-bulk-scan/aat.yaml
> +      image: hmctspublic.azurecr.io/sscs/bulk-scan:prod-0b474b1-20220328103050 #{"$imagepolicy": "flux-system:sscs-bulk-scan"}
Image should be in base Helm Release if not overriding prod image.

2022-03-30 07:04 UTC, chrisorisawayi commented on k8s/namespaces/sscs/sscs-bulk-scan/aat.yaml
> +      image: hmctspublic.azurecr.io/sscs/bulk-scan:prod-0b474b1-20220328103050 #{"$imagepolicy": "flux-system:sscs-bulk-scan"}
Image should be in base Helm Release if not overriding prod image.

2022-03-30 07:04 UTC, chrisorisawayi commented on k8s/namespaces/sscs/sscs-bulk-scan/perftest.yaml
> +      image: hmctspublic.azurecr.io/sscs/bulk-scan:prod-0b474b1-20220328103050 #{"$imagepolicy": "flux-system:sscs-bulk-scan"}
Image should be in base Helm Release if not overriding prod image.

2022-03-30 07:04 UTC, chrisorisawayi commented on k8s/namespaces/sscs/sscs-bulk-scan/perftest.yaml
> +      image: hmctspublic.azurecr.io/sscs/bulk-scan:prod-0b474b1-20220328103050 #{"$imagepolicy": "flux-system:sscs-bulk-scan"}
Image should be in base Helm Release if not overriding prod image.

2022-03-30 07:08 UTC, chrisorisawayi commented on k8s/namespaces/sscs/sscs-hearings-api/ithc.yaml
> +      image: hmctspublic.azurecr.io/sscs/hearings-api:prod-2d34469-20220325150900 #{"$imagepolicy": "flux-system:sscs-hearings-api"}
Image should be in base Helm Release if not overriding prod image.  Make similar changes in applicable environments.

2022-04-05 12:31 UTC, thomast1906 requested changes
AS prod is not to be included, can you remove prod references.

also missing base sscs as per discussion. Example to show what is required: https://github.com/hmcts/cnp-flux-config/blob/master/k8s/namespaces/camunda/kustomization.yaml#L5-L7

2022-04-05 12:32 UTC, thomast1906 requested changes
AS prod is not to be included, can you remove prod references.

also missing base sscs as per discussion. Example to show what is required: [https://github.com/hmcts/cnp-flux-config/blob/master/k8s/namespaces/camunda/kustomization.yaml#L5-L7](https://github.com/hmcts/cnp-flux-config/blob/master/k8s/namespaces/camunda/kustomization.yaml?rgh-link-date=2022-04-05T12%3A31%3A30Z#L5-L7)

2022-04-11 12:27 UTC, thomast1906 commented on k8s/aat/common-overlay/sscs/kustomization.yaml
> +- ../../../namespaces/sscs/sscs-hearings-api/sscs-hearings-api.yaml
I am assuming once all apps are kustomized - you will be moving this into namespaces/sscs - rather thn a specific per each app

2022-04-11 12:27 UTC, thomast1906 approved these changes

2022-04-11 12:32 UTC, ss-evoco approved these changes

2022-04-11 12:37 UTC, merged