DTSBPS-1007: Fixed kustomization
hmcts/cnp-flux-config pull request #16630
Opened 2022-07-11 14:44 UTC by apereverzin

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSBPS-1007

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-07-11 15:05 UTC, adusumillipraveen commented on k8s/namespaces/bsp/bulk-scan-payment-processor/bsp-storage-account-creds-demo.yaml
> +  name: bsp-storage-account-creds-demo
this name and filename should match the one in https://github.com/hmcts/cnp-flux-config/pull/16630/files#diff-f40dcaf10cd822b2c4e349e646c7ab220909ff2e87153dd5e8b449ac61c2bc26R16

2022-07-11 15:05 UTC, adusumillipraveen requested changes
pls fix filenames and sealedsecret.name

2022-07-11 16:31 UTC, apereverzin commented
@adusumillipraveen 
Is this what you mean: https://github.com/hmcts/cnp-flux-config/pull/16630/commits/0cad01963d9a2c55b9f117bfa923830b4b80a056

2022-07-12 11:44 UTC, adusumillipraveen approved these changes

2022-07-12 11:57 UTC, alivenichoppa approved these changes

2022-07-12 11:58 UTC, merged