sscs-tribunal-frontend-chart-bump
hmcts/cnp-flux-config pull request #16794
Opened 2022-07-19 14:35 UTC by rmurphy-hmcts

### Change description ###

- Cleanup of kustomize files. 
- Update to prod file to pull latest Chart version

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-07-19 14:45 UTC, reespozzi approved these changes

2022-07-19 14:46 UTC, reespozzi requested changes
Could you use latest like https://github.com/hmcts/cnp-flux-config/blob/43aeab84e54f650b8b27fa875ff5d904be2b71fa/k8s/namespaces/sscs/sscs-tribunals-frontend/aat.yaml#L6 instead? Or move that master reference into base and patch accordingly

2022-07-19 15:30 UTC, rmurphy-hmcts commented
> Could you use latest like
> 
> https://github.com/hmcts/cnp-flux-config/blob/43aeab84e54f650b8b27fa875ff5d904be2b71fa/k8s/namespaces/sscs/sscs-tribunals-frontend/aat.yaml#L6
> 
> instead? Or move that master reference into base and patch accordingly

Prod file updated and all env files updated by moving the chart section to the base yaml file

2022-07-20 08:49 UTC, reespozzi approved these changes

2022-07-20 08:49 UTC, merged