scaled up ccd data store on prod01 for upgrade on prod00
hmcts/cnp-flux-config pull request #17119
Opened 2022-08-05 18:32 UTC by darren221980

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/DTSPO-8034

### Change description ###

Scaled up ccd-data-store while on prod 01 while prod 00 is taken offline for aks upgrade.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2022-08-08 12:21 UTC, ciaranca commented on k8s/prod/cluster-00-overlay/ccd/kustomization.yaml
> +- ../../../namespaces/ccd/ccd-definition-store-api/patches/prod-01.yaml
Conflict here, prod-01 should be in cluster-01-overlay

2022-08-08 12:21 UTC, ciaranca commented on k8s/prod/cluster-00-overlay/ccd/kustomization.yaml
> +- ../../../namespaces/ccd/ccd-data-store-api/patches/prod-01.yaml
Same here, move to cluster-01-overlay

2022-08-08 19:56 UTC, darren221980 commented on k8s/prod/cluster-00-overlay/ccd/kustomization.yaml
> +- ../../../namespaces/ccd/ccd-data-store-api/patches/prod-01.yaml
now fixed.

2022-08-23 07:27 UTC, reespozzi approved these changes

2022-08-23 07:27 UTC, reespozzi requested changes
Failing checks

2022-08-25 09:58 UTC, closed without merging