RWA-1095-cluster
hmcts/cnp-flux-config pull request #17229
Opened 2022-08-11 14:30 UTC by Lee365

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RWA-1095

### Change description ###
RWA-1095 wa batch reconfiguration job to be added to cluster

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-08-11 14:48 UTC, vgulapally submitted a review, later dismissed

2022-08-12 09:17 UTC, adusumillipraveen requested changes
Sorry, this is not needed.

2022-08-12 11:24 UTC, adusumillipraveen approved these changes

2022-08-12 12:13 UTC, serdaroguzhanakin approved these changes

2022-08-12 12:14 UTC, merged