HMC-387 Configure hmc-operational-reports-runner to run daily
hmcts/cnp-flux-config pull request #17640
Opened 2022-09-05 13:23 UTC by RebeccaBaker

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/HMAN-387

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-09-05 14:00 UTC, danlysiak submitted a review, later dismissed

2022-09-06 13:25 UTC, markdathornehmcts submitted a review, later dismissed

2022-09-09 10:53 UTC, willwatters submitted a review, later dismissed

2022-09-09 11:05 UTC, adusumillipraveen requested changes
All new apps should go to flux v2 folders

2022-09-12 11:33 UTC, danlysiak approved these changes

2022-09-12 11:36 UTC, adusumillipraveen commented on apps/hmc/hmc-operational-reports-runner/hmc-operational-reports-runner.yaml
> +    hmcts.github.com/prod-automated: enabled
i don't think u need them now
```suggestion
```

2022-09-12 11:50 UTC, adusumillipraveen commented on apps/hmc/hmc-operational-reports-runner/hmc-operational-reports-runner.yaml
> +    hmcts.github.com/prod-automated: enabled
i don't think u need them for flux v2
```suggestion
```

2022-09-12 12:43 UTC, danlysiak approved these changes

2022-09-12 12:46 UTC, merged