Dtspb 2886 automate case move in out dormant
hmcts/cnp-flux-config pull request #17662
Opened 2022-09-06 10:41 UTC by IswaryaPepakayala

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSPB-2886
https://tools.hmcts.net/jira/browse/DTSPB-2800

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2022-09-08 09:59 UTC, sanjayparekh-hmcts approved these changes

2022-09-08 10:36 UTC, srochani submitted a review, later dismissed

2022-09-08 12:22 UTC, adusumillipraveen requested changes
I am guessing this is a new app, all new apps need to go to flux v2 config. https://github.com/hmcts/cnp-flux-config/blob/master/docs/app-deployment-v2.md

2022-09-08 15:45 UTC, IswaryaPepakayala commented
@adusumillipraveen We have created ticket to migrate to flux v2 .
https://tools.hmcts.net/jira/browse/DTSPB-3009
We want to change this with help of platop because lot of config files need to be updated.Can you please approve this pull request

2022-09-13 10:59 UTC, pankajhmcts requested changes
Please explain the reason for this change, as I can see 462 files updated.

2022-09-26 04:16 UTC, closed without merging