Civil setup for flux v2
hmcts/cnp-flux-config pull request #18153
Opened 2022-10-03 11:40 UTC by chris-pateman

### Change description ###
Issues with Test and ITHC, so setup on Flux V2

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ x ] No
```

2022-10-03 12:54 UTC, louisehuyton approved these changes

2022-10-03 13:15 UTC, vasudevganesanhmcts submitted a review, later dismissed

2022-10-03 13:24 UTC, thomast1906 requested changes
- Can you cleanup folders you are removing in Flux v1?
- Why not removing Civil flux v1 aat?
- Bases not added to clusters/*

2022-10-03 13:45 UTC, staceywilson approved these changes

2022-10-27 15:04 UTC, adusumillipraveen commented on apps/civil/preview/base/kustomization.yaml
> +  - ../../../rbac/nonprod-role.yaml
Not needed as teams have better permissions on preview
```suggestion
```

2022-10-27 15:30 UTC, adusumillipraveen approved these changes

2022-10-28 09:31 UTC, adusumillipraveen approved these changes

2022-10-28 10:22 UTC, HarryH96 approved these changes

2022-10-28 10:23 UTC, adusumillipraveen approved these changes

2022-10-28 10:27 UTC, merged