RWA-2011 New cronjob for fixing null event timestamp in AAT
hmcts/cnp-flux-config pull request #19181
Opened 2022-11-15 15:25 UTC by DennisHoV1

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RWA-2011

### Change description ###
-New message job for fixing null event timestamp in AAT

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2022-11-16 08:48 UTC, timja requested changes
All new apps / jobs must use flux v2

2022-11-16 16:59 UTC, dharmendrak reviewed
changes in k8s/namespaces/wa/ is not required based on new changes

2022-11-17 13:08 UTC, dharmendrak approved these changes

2022-11-17 13:28 UTC, dharmendrak commented
> All new apps / jobs must use flux v2

followed v2 now

2022-11-17 13:43 UTC, timja approved these changes

2022-11-17 13:50 UTC, dharmendrak approved these changes

2022-11-18 21:48 UTC, merged