updated config
hmcts/cnp-flux-config pull request #20761
Opened 2023-02-06 18:09 UTC by hmcts-kodatala

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2023-02-06 19:17 UTC, thomast1906 requested changes
Looks to be values from demo - these are not needed for other envs

2023-02-06 19:17 UTC, thomast1906 commented on apps/fis/fis-hmc-api/ithc.yaml
> +      disableIngressClassAnnotation: true
Looks to be values from demo - these are not needed for other envs

2023-02-07 09:05 UTC, hannah38 commented on apps/fis/fis-hmc-api/perftest.yaml
> +      image: hmctspublic.azurecr.io/fis/hmc-api:prod-2a50409-20230126163420 #{"$imagepolicy": "flux-system:demo-fis-hmc-api"}
```suggestion
      image: hmctspublic.azurecr.io/fis/hmc-api:prod-2a50409-20230126163420 #{"$imagepolicy": "flux-system:perftest-fis-hmc-api"}
```

2023-02-07 09:06 UTC, hannah38 commented on apps/fis/fis-hmc-api/ithc.yaml
> +      image: hmctspublic.azurecr.io/fis/hmc-api:prod-2a50409-20230126163420 #{"$imagepolicy": "flux-system:demo-fis-hmc-api"}
```suggestion
      image: hmctspublic.azurecr.io/fis/hmc-api:prod-2a50409-20230126163420 #{"$imagepolicy": "flux-system:ithc-fis-hmc-api"}
```

2023-02-07 09:25 UTC, hannah38 commented on apps/fis/fis-hmc-api/ithc.yaml
> +      image: hmctspublic.azurecr.io/fis/hmc-api:prod-2a50409-20230126163420 #{"$imagepolicy": "flux-system:perftest-fis-hmc-api"}
```suggestion
      image: hmctspublic.azurecr.io/fis/hmc-api:prod-2a50409-20230126163420 #{"$imagepolicy": "flux-system:ithc-fis-hmc-api"}
```

2023-02-07 09:43 UTC, hannah38 commented on apps/fis/automation/kustomization.yaml
> +   - ../fis-hmc-api/ithc-image-policy.yaml
Indentation is off here

2023-02-07 09:53 UTC, hannah38 commented on apps/fis/fis-hmc-api/demo.yaml
> +          DUMMY_VAR_TO_REDEPLOY: 1
Failing checks here because of indentation "expected 8 but found 10"

2023-02-07 18:36 UTC, hannah38 approved these changes

2023-02-07 19:05 UTC, hmcts-shajahan approved these changes

2023-02-08 09:08 UTC, merged