PCQ-1880 remove autoscaling from loader and consolidation
hmcts/cnp-flux-config pull request #30057
Opened 2024-03-22 16:25 UTC by priyankaVerma21

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/PCQ-1880

### Change description ###
Remove autoScaling from loader and consolidation

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-03-22 17:00 UTC, MartinYSpasov requested changes

2024-03-22 17:00 UTC, MartinYSpasov commented on apps/pcq/pcq-frontend/prod.yaml
>          maxReplicas: 3
What's the autoscaling rule here?

2024-03-22 17:00 UTC, MartinYSpasov commented on apps/pcq/pcq-backend/prod.yaml
>          maxReplicas: 3
What's the autoscaling rule here?

2024-03-24 13:10 UTC, priyankaVerma21 commented on apps/pcq/pcq-backend/prod.yaml
>          maxReplicas: 3
It has been enabled in values.yaml

2024-03-24 13:10 UTC, priyankaVerma21 commented on apps/pcq/pcq-frontend/prod.yaml
>          maxReplicas: 3
It has been enabled in values.yaml

2024-03-25 10:44 UTC, priyankaVerma21 commented
Closing this PR . will do backend First

2024-03-25 10:44 UTC, closed without merging