1777 on demo - DO NOT MERGE
hmcts/cnp-flux-config pull request #30383
Opened 2024-04-11 15:09 UTC by kasi-subramaniam

Test the Fix for 1777 on demo - 

Update the service payments url to point to the FeePay URL as follows. This need to be done for both MO and AO on demo environment. 

SERVICES_PAYMENTS_URL: http://payment-api-int-demo.service.core-compute-demo.internal

2024-04-12 10:54 UTC, andywilkinshmcts requested changes
Also need to do it for AO

2024-04-12 10:56 UTC, kasi-subramaniam commented
> Also need to do it for AO

Andy , both AO and MO are referred in this PR itself  

> Also need to do it for AO

2024-04-12 11:47 UTC, kasi-subramaniam commented
> Also need to do it for AO

MC , MO and AO - are all changed now .

2024-04-15 08:44 UTC, andywilkinshmcts approved these changes

2024-04-15 08:44 UTC, merged