SIDM-9187 add profile bridge to preview
hmcts/cnp-flux-config pull request #30769
Opened 2024-04-29 14:53 UTC by jburke-idam

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/SIDM-9187

### Change description ###

Deploy user profile bridge to preview

### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [x] README and other documentation has been updated / added (if needed)
- [x] tests have been updated / new tests has been added (if needed)
- [x] Does this PR introduce a breaking change

2024-04-29 15:07 UTC, kremi approved these changes

2024-04-29 16:17 UTC, thomast1906 requested changes
You need to add a base config - either append to here or in the idam/base (this goe to all envs tho)

https://github.com/hmcts/cnp-flux-config/blob/c0089816f0db593c41a1aa43dd2e51a83d2501a3/apps/idam/preview/base/kustomization.yaml#L5

2024-04-30 07:07 UTC, thomast1906 approved these changes

2024-04-30 08:56 UTC, kremi approved these changes

2024-04-30 08:56 UTC, merged