HwF processing- Cron job for checking payment status
hmcts/cnp-flux-config pull request #32459
Opened 2024-06-19 15:54 UTC by sahaSonali

### Jira link (if applicable)

https://tools.hmcts.net/jira/browse/PRL-5906

### Change description ###

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-06-24 09:53 UTC, yogendraU requested changes

2024-06-24 09:53 UTC, yogendraU commented on apps/private-law/prl-cron-hwf-citizen-update-state/prl-cron-fm5-reminder.yaml
> +  releaseName: prl-cron-hwf-citizen-update-state
Hi @sahaSonali The file name is incorrect. Please correct it. 

Also, there are few more files you need to add reference of the cron job to. Please refer to below PR.
https://github.com/hmcts/cnp-flux-config/pull/32508

2024-06-24 09:53 UTC, yogendraU commented on apps/private-law/prl-cron-hwf-citizen-update-state/prod.yaml
> +      schedule: 0 * * * *
For Prod.yaml, please change the schedule until we merge COS and CCD changes to Production

2024-08-28 16:34 UTC, channa-patil submitted a review, later dismissed

2024-08-29 09:03 UTC, channa-patil approved these changes

2024-08-29 09:07 UTC, cpareek approved these changes

2024-08-29 10:22 UTC, merged