Add hmcts access file to AAT
hmcts/cnp-flux-config pull request #33181
Opened 2024-07-24 16:22 UTC by nikola-naydenov-hmcts

2024-07-24 16:26 UTC, chandkanuri submitted a review, later dismissed

2024-07-25 07:40 UTC, kremi submitted a review, later dismissed

2024-07-25 08:45 UTC, thomast1906 requested changes
hmmm, aat.yaml in Preview?

I see : https://github.com/hmcts/cnp-flux-config/blob/00e0234f630d2015c96dfa29ad18327e8d41c698/apps/idam/idam-hmcts-access/preview.yaml - is that a typo?

2024-07-25 09:25 UTC, nikola-naydenov-hmcts commented
> hmmm, aat.yaml in Preview?
> 
> I see : https://github.com/hmcts/cnp-flux-config/blob/00e0234f630d2015c96dfa29ad18327e8d41c698/apps/idam/idam-hmcts-access/preview.yaml - is that a typo?

I am trying to add a file for AAT, we do have a deployment in Preview as well. I am not sure what you mean here.

2024-07-25 11:00 UTC, thomast1906 approved these changes

2024-07-25 11:00 UTC, merged