FPET-1115-added login to bring up pods for fis-bulk-scan-api
hmcts/cnp-flux-config pull request #33953
Opened 2024-08-27 11:31 UTC by mohitvijay45

### Jira link

See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)

### Change description

### Testing done

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-08-27 11:32 UTC, sairamkantheti1 approved these changes

2024-08-27 13:45 UTC, hannah38 requested changes

2024-08-27 13:45 UTC, hannah38 commented on apps/fis/fis-bulk-scan-api/demo-image-policy.yaml
Hi, can you add this new demo-image-policy similar to https://github.com/hmcts/cnp-flux-config/blob/17ea948b2c1f6f0189a0ddd817c5735d8a5cb81b/apps/fis/automation/kustomization.yaml#L4-L5

2024-08-27 13:58 UTC, mohitvijay45 commented on apps/fis/fis-bulk-scan-api/demo-image-policy.yaml
Hi @hannah38 made the suggested changes.. Thank You

2024-08-28 09:24 UTC, hannah38 approved these changes

2024-08-28 09:26 UTC, sairamkantheti1 approved these changes

2024-08-28 09:28 UTC, merged