Add Kustomize config for T&Cs
hmcts/cnp-flux-config pull request #6048
Opened 2020-09-17 08:57 UTC by ernestman28

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2020-09-17 09:31 UTC, adusumillipraveen requested changes
They should be deleted from k8s/env/common/xui for this to work

2020-09-17 09:31 UTC, adusumillipraveen commented on k8s/namespaces/xui/xui-terms-and-conditions/aat.yaml
> +  annotations:
these should be automatic and dont need to add it.

2020-09-17 09:31 UTC, adusumillipraveen commented on k8s/namespaces/xui/xui-terms-and-conditions/aat.yaml
> +      ingressHost: xui-terms-and-conditions-aat.service.core-compute-aat.internal
This should ideally come from template

2020-09-17 09:31 UTC, adusumillipraveen commented on k8s/namespaces/xui/xui-terms-and-conditions/demo.yaml
> +      ingressHost: xui-terms-and-conditions-demo.service.core-compute-demo.internal
This should come from base chart as templated

2020-09-17 09:31 UTC, adusumillipraveen commented on k8s/namespaces/xui/xui-terms-and-conditions/prod.yaml
> +  annotations:
Don't need to add this, they will be added by us by default

2020-09-18 08:02 UTC, ernestman28 commented on k8s/namespaces/xui/xui-terms-and-conditions/aat.yaml
> +      ingressHost: xui-terms-and-conditions-aat.service.core-compute-aat.internal
sure

2020-09-18 12:03 UTC, adusumillipraveen approved these changes

2020-09-18 12:03 UTC, adusumillipraveen commented on k8s/namespaces/xui/xui-terms-and-conditions/aat.yaml
> +      #ingressHost: xui-terms-and-conditions-aat.service.core-compute-aat.internal
```suggestion
  
```

2020-09-18 12:19 UTC, adusumillipraveen approved these changes

2020-09-18 15:32 UTC, Mo-Lala84 approved these changes
Done

2020-09-18 16:21 UTC, merged