Add raw manifest in kustomize for csi driver
hmcts/cnp-flux-config pull request #6437
Opened 2020-10-14 08:16 UTC by avi-hmcts

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2020-10-14 08:17 UTC, timja commented on k8s/namespaces/admin/csi-secret-store-provider/kustomization.yaml
> +  - https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/deployment/provider-azure-installer.yaml
don't use master, use released versions

2020-10-14 08:29 UTC, adusumillipraveen requested changes
Also, would be good to test in an env? just to be sure the patch u did doesnt have any impact.

2020-10-14 08:29 UTC, adusumillipraveen commented on k8s/namespaces/admin/csi-secret-store-provider/kustomization.yaml
> +  - https://raw.githubusercontent.com/Azure/secrets-store-csi-driver-provider-azure/master/deployment/provider-azure-installer.yaml
Must point to release tag than master as we don't want breaking changes applied .

2020-10-15 08:17 UTC, avi-hmcts reviewed
@adusumillipraveen As per our discussion made the changes to test the raw manifest for the csi driver and azure provider initially on the sandbox

2020-10-15 09:31 UTC, closed without merging