Authorise Role Assignment Service
hmcts/cnp-flux-config pull request #6958
Opened 2020-11-11 22:16 UTC by hemantt

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2020-11-11 22:22 UTC, MSancaktutar requested changes
Could you enable on ITHC and Perftest, as well please?

2020-11-11 22:25 UTC, MSancaktutar reviewed
Sorry, but if they need to access case details, this is not the correct env var. In any case, general s2s authorisation will be (also) required.

2020-11-18 09:53 UTC, smathangi commented on k8s/aat/common/ccd/data-store-api.yaml
> +        DATA_STORE_S2S_AUTHORISED_SERVICES: am_role_assignment_service
It just override chart's env variable. So, you might need to include all other values from here https://github.com/hmcts/ccd-data-store-api/blob/master/charts/ccd-data-store-api/values.yaml#L34

2020-11-18 09:53 UTC, smathangi commented on k8s/aat/common/ccd/data-store-api.yaml
> +        DUMMY_RESTART_VAR: 0
delete these dummy variables

2020-11-18 12:20 UTC, MSancaktutar requested changes
This will deny access to all current allowed list configured in chart config.
Please **make sure you copy the full list from respective configs** and append am_role_assignment_service.

2020-11-18 12:22 UTC, closed without merging