AAC perftest config
hmcts/cnp-flux-config pull request #7562
Opened 2021-01-06 13:58 UTC by hemantt

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-01-06 14:01 UTC, danlysiak submitted a review, later dismissed

2021-01-06 14:36 UTC, nathan-clark commented on k8s/namespaces/aac/manage-case-assignment/perftest.yaml
> +      image: hmctspublic.azurecr.io/aac/manage-case-assignment:pr-184-2daeecca
https://github.com/hmcts/cnp-flux-config/blob/f956bc8704a8895d282f6356b7990eb70247c43b/k8s/namespaces/aac/kustomization.yaml#L3

should be aac?

2021-01-07 10:36 UTC, jmcadam requested changes

2021-01-07 10:36 UTC, jmcadam commented on k8s/namespaces/aac/manage-case-assignment/perftest.yaml
> +        CCD_DEFINITION_STORE_API_BASE_URL: http://ccd-definition-store-api-demo.service.core-compute-demo.internal
perftest instead of demo?

2021-01-08 13:46 UTC, jmcadam commented on k8s/namespaces/aac/manage-case-assignment/perftest.yaml
> +        CCD_DEFINITION_STORE_API_BASE_URL: http://ccd-definition-store-api-demo.service.core-compute-demo.internal
@hemantt one for you mate!

2021-02-09 15:43 UTC, smathangi approved these changes

2021-02-09 15:46 UTC, smathangi requested changes

2021-02-09 15:46 UTC, smathangi commented on k8s/perftest/common-overlay/aac/kustomization.yaml
> +- ../../../namespaces/aac/manage-case-assignment/ithc.yaml
ithc entry should go to it's own kustomization file

2021-02-09 16:06 UTC, smathangi approved these changes

2021-02-09 18:12 UTC, danlysiak submitted a review, later dismissed

2021-02-16 10:43 UTC, jmcadam approved these changes
👍

2021-02-16 10:47 UTC, TomKimber approved these changes

2021-02-16 10:50 UTC, smathangi approved these changes

2021-02-16 10:50 UTC, hemantt reviewed
done

2021-02-16 10:50 UTC, merged