RDM-11075: Revert back key vault config for case-man-web in demo
hmcts/cnp-flux-config pull request #8055
Opened 2021-02-08 12:56 UTC by rajaram-nagarajan

### JIRA link ###

https://tools.hmcts.net/jira/browse/RDM-11075

### Change description ###

Reverted back key vault config for case-man-web in demo

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2021-02-08 14:57 UTC, danlysiak submitted a review, later dismissed

2021-02-11 10:09 UTC, MSancaktutar approved these changes
LGTM

2021-02-11 10:49 UTC, hemantt requested changes
Please hold off this change until Pay version release next week

2021-02-12 14:14 UTC, closed without merging

2021-02-12 14:14 UTC, rajaram-nagarajan commented
Not required