add namespace for ICP
hmcts/cnp-flux-config pull request #8178
Opened 2021-02-12 16:36 UTC by benouaer

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-02-12 16:38 UTC, yogesh-hullatti submitted a review, later dismissed

2021-02-15 11:55 UTC, adusumillipraveen requested changes
no, you shouldn't need this.

2021-02-15 16:38 UTC, yogesh-hullatti approved these changes

2021-02-15 16:42 UTC, rajkatla-hmcts approved these changes

2021-02-15 16:42 UTC, adusumillipraveen approved these changes

2021-02-15 16:42 UTC, merged