SSCS-7330 Non Prod SSCS MYA Service and Redirect
hmcts/cnp-flux-config pull request #8281
Opened 2021-02-18 11:26 UTC by danhamilton

**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

2021-02-18 15:40 UTC, chrisdavecm approved these changes

2021-02-18 17:20 UTC, adusumillipraveen requested changes
All new apps should use kustomize.

https://github.com/hmcts/cnp-flux-config/blob/master/docs/app-deployment.md

2021-02-19 13:23 UTC, adusumillipraveen commented on k8s/namespaces/sscs/sscs-mya-frontend/sscs-mya-frontend.yaml
> +    flux.weave.works/tag.nodejs: glob:prod-*
```suggestion
```

2021-02-19 13:23 UTC, adusumillipraveen commented on k8s/namespaces/sscs/sscs-mya-frontend/sscs-mya-frontend.yaml
> +    retry: true
```suggestion
```

2021-02-19 13:23 UTC, adusumillipraveen commented on k8s/namespaces/sscs/sscs-mya-frontend/sscs-mya-frontend.yaml
> +      enableKeyVaults: true
```suggestion
```

2021-02-19 13:23 UTC, adusumillipraveen commented on k8s/namespaces/sscs/sscs-mya-frontend/pertftest.yaml
> +      environment: perftest
```suggestion
```

2021-02-19 13:23 UTC, adusumillipraveen commented on k8s/namespaces/sscs/sscs-mya-frontend/demo.yaml
> +      environment: demo
```suggestion
```

2021-02-19 13:23 UTC, adusumillipraveen commented on k8s/namespaces/sscs/sscs-mya-frontend/aat.yaml
> +      environment: aat
```suggestion
```

2021-02-19 13:23 UTC, adusumillipraveen commented on k8s/aat/common-overlay/kustomization.yaml
> +  - sscs
```suggestion
```

2021-02-19 13:24 UTC, adusumillipraveen commented on CODEOWNERS
> +k8s/**/common/sscs/sscs-mya-frontend.yaml @hmcts/sscs
```suggestion
```

2021-02-19 15:41 UTC, closed without merging