RDM-11717: Develop Builds Dashboard
hmcts/cnp-flux-config pull request #9027
Opened 2021-04-07 13:03 UTC by kiran-yenigala-hmcts

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/RDM-11717

### Change description ###

CCD Develop build dashboard

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X ] No
```

2021-04-07 13:16 UTC, MSancaktutar commented on k8s/namespaces/jenkins/patches/cftptl/cluster-00/jenkins.yaml
> +                      ^HMCTS_.*CDM.*\/(?!.*ccd-admin-web-api).+\/develop
Well, this regex should rather pick the PR builds with specific pr numbers.
Eg. HMCTS_CDM/job/ccd-data-store-api/view/change-requests/job/PR-1260/

2021-04-07 13:16 UTC, MSancaktutar requested changes
Pls see my comment.

2021-04-13 15:22 UTC, MSancaktutar commented on k8s/namespaces/jenkins/patches/cftptl/cluster-00/jenkins.yaml
> +                      ^HMCTS_.*CDM.*\/(.*ac-manage-case-assignment.*PR-180|.*ccd-admin-web.*PR-325|.*ccd-api-gateway.*PR-353|.*ccd-case-activity-api.*PR-256|.*ccd-case-print-service.*PR-260|.*ccd-dat
data store is 1260

2021-04-13 15:27 UTC, MSancaktutar commented on k8s/namespaces/jenkins/patches/cftptl/cluster-00/jenkins.yaml
> +                      ^HMCTS_.*CDM.*\/(.*ac-manage-case-assignment.*PR-180|.*ccd-admin-web.*PR-325|.*ccd-api-gateway.*PR-353|.*ccd-case-activity-api.*PR-256|.*ccd-case-print-service.*PR-260|.*ccd-dat
pls also add case man web pr 1043.

2021-04-13 20:42 UTC, MSancaktutar requested changes
pls see 2 comments

2021-04-15 09:06 UTC, MSancaktutar approved these changes
LGTM

2021-04-19 09:41 UTC, hemantt approved these changes

2021-04-19 09:43 UTC, timja approved these changes
🙈

2021-04-19 15:28 UTC, MSancaktutar approved these changes
LGTM

2021-04-19 15:28 UTC, merged